### PR TITLE
#168131443 Users should be able to like/unlike an accommodation facility

### PR DESCRIPTION
**Pull request by drayzii**
#### What does this PR do?
Allows users to like/unlike an accommodation facility
#### Description of Task to be completed?
- Implement liking and disliking accommodations
#### How should this be manually tested?
- Clone this repo
- Checkout to branch `ft-like-unlike-accommodations-168131443`
- Run `npm test`
- Run migrations `npm run db-migrate:dev`
- Run the application with `npm run start:dev` and after you successfully log in make this requests `PATCH` request to `api/v1/accommodations/{accommodation id}/like`
- After you make the request you should see responses that look like the ones in the screenshot
- Alternatively, you can test using the Heroku Review App `https://mervels-bn-backend-stagi-pr-39.herokuapp.com`
#### Any background context you want to provide?
- When you hit endpoint for the first time it likes (Screenshot 1), when you hit it again it dislikes (Screenshot 2).
- When you fetch all the accommodations, you will see the number of likes (Screenshot 3)
- When you fetch one accommodation, you will see the number and all the likes (Screensho4)
#### What are the relevant pivotal tracker stories?
[#168131443](https://www.pivotaltracker.com/story/show/168131443)
#### Screenshots (if appropriate)

Screenshot 1
image

Screenshot 2
image

Screenshot 3
image

Screenshot 4
image

#### Questions:
N/A

### CODE REVIEW

**Comment by Bahatiroben** [comment]
is it possible to unlike before like?

**Comment by drayzii** [comment]
> is it possible to unlike before like?

No, you can't, if you hit it for the first time it always likes. The next time unllikes, then likes...

**Review by Bahatiroben — APPROVED** [review]
looks good. resolve the conflicts, then you're good to go.

**Review by j0flintking02 — APPROVED** [review]
LGTM

**Review by Paulvitalis200 — APPROVED** [review]

**Pull request merged**
