### PR TITLE
#168238480 Add pull request template

### PR DESCRIPTION
**Pull request by Bahatiroben**
#### What does this PR do?
- it creates a preloaded pull request template
#### Description of Task to be completed?
```
- for consistency, every pull request will reflect the same template
```
#### How should this be manually tested?
```
- clone the repo
- work on a feature
- raise a PR

- YOU SHOULD see a preloaded template which prompts you to answer some questions. 
- try to be as brief as possible about your feature implementation
- under the relevant pivotal tracker stories, `[ ]` can contain a PT story ID, and `( )` 
contain the link to PT story. otherwise, `N/A`
- putting `N/A` (not applicable) under the prompt you feel you have no response to, will be good for consistency
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168238480](https://www.pivotaltracker.com/story/show/168238480)
#### Screenshots (if appropriate)
Screen Shot 2019-09-02 at 15 24 34

#### Questions:
N/A

### CODE REVIEW

**Review by j0flintking02 — APPROVED** [review]
LGMT

**Review by willywax — APPROVED** [review]

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @Bahatiroben please put this template file inside a `.github` folder on the root directory before I merge it.

**Review by Paulvitalis200 — COMMENTED** [review]
Also, the title of the PR after writing the story ID should be the same as that of the story in the pivotal tracker board.

**Review by Paulvitalis200 — COMMENTED** [review]
Please amend your commit message by renaming the scope of your commit message. It should not have a space in between and should be e.g `pull-request-template` and not `PR-template`

**Comment by Bahatiroben** [comment]
> Please amend your commit message by renaming the scope of your commit message. It should not have a space in between and should be e.g `pull-request-template` and not `PR-template`

worked on it.

**Review by Paulvitalis200 — APPROVED** [review]

**Review by Paulvitalis200 — APPROVED** [review]
Good work on adding the template.

**Pull request merged**
