### PR TITLE
#168257936 Setup babel (ES6)

### PR DESCRIPTION
**Pull request by j0flintking02**
#### What does this PR do?
Sets up the project to use the babel compiler
#### Description of Task to be completed?
- adds the development and production script
- add modules for development(nodemon, morgan)
#### How should this be manually tested?
- make sure you have MongoDB installed
- Run npm install
- Run `npm start` for production or `npm start:dev` for development
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168257936](https://www.pivotaltracker.com/story/show/168257936)
#### Screenshots (if appropriate)
Screen Shot 2019-09-03 at 13 13 45

#### Questions:
N/A

### CODE REVIEW

**Comment by drayzii** [comment]
Check your commit message. There is an error (stepup)

**Comment by j0flintking02** [comment]
> Check your commit message. There is an error (stepup)

thanks for that insight just fixed it

**Comment by drayzii** [comment]
Looks good but why did you add morgan?

**Review by willywax — APPROVED** [review]
Looks good

**Comment by j0flintking02** [comment]
> Looks good but why did you add morgan?

I have removed it

**Review by drayzii — APPROVED** [review]

**Review by Paulvitalis200 — APPROVED** [review]
Good work on this setup.

**Pull request merged**
